"""Regenerate `charmm_ubq_openmm.txt`, the CHARMM36m reference for the tests in `tests/charmm.rs`.

OpenMM's `charmm36_2024.xml` is derived from toppar_c36_jul24, as are the CHARMM files in
`param_data/charmm`. We use ubiquitin (1UBQ; protein atoms, first alternate locations), and let
OpenMM add hydrogens at pH 7. The output holds the structure (atoms, bonds), OpenMM's partial
charges, and energy components in vacuum, without cutoffs.

Usage: python regenerate_charmm_reference.py path/to/1ubq.cif
(e.g. molchanica/molecules/1ubq.cif, or from RCSB.) Tested with OpenMM 8.3.1.
"""

import math
import sys

import openmm as mm
from openmm import app, unit

KJ_TO_KCAL = 1 / 4.184
# OpenMM's Coulomb constant, in kJ/mol nm e^-2.
ONE_4PI_EPS0 = 138.935456

def torsion_angle(p0, p1, p2, p3):
    """The IUPAC dihedral angle, in radians, as OpenMM computes it."""
    sub = lambda u, v: [u[i] - v[i] for i in range(3)]
    dot = lambda u, v: sum(u[i] * v[i] for i in range(3))
    cross = lambda u, v: [
        u[1] * v[2] - u[2] * v[1],
        u[2] * v[0] - u[0] * v[2],
        u[0] * v[1] - u[1] * v[0],
    ]
    b0, b1, b2 = sub(p0, p1), sub(p2, p1), sub(p3, p2)
    b1_len = math.sqrt(dot(b1, b1))
    b1n = [v / b1_len for v in b1]
    v = sub(b0, [dot(b0, b1n) * x for x in b1n])
    w = sub(b2, [dot(b2, b1n) * x for x in b1n])
    return math.atan2(dot(cross(b1n, v), w), dot(v, w))


cif = app.PDBxFile(sys.argv[1])
modeller = app.Modeller(cif.topology, cif.positions)
modeller.delete([r for r in modeller.topology.residues() if r.name == "HOH"])

ff = app.ForceField("charmm36_2024.xml")
modeller.addHydrogens(ff, pH=7.0)
top = modeller.topology
# Rounded as written, so the energies are for the positions in the file.
pos_nm = [[round(10 * v, 4) / 10 for v in p.value_in_unit(unit.nanometer)] for p in modeller.positions]

system = ff.createSystem(top, nonbondedMethod=app.NoCutoff, constraints=None, rigidWater=False)

names = {
    mm.HarmonicBondForce: "bond_ub",  # Bonds and Urey-Bradley terms
    mm.HarmonicAngleForce: "angle",
    mm.PeriodicTorsionForce: "dihedral",
    mm.CustomTorsionForce: "improper",
    mm.CMAPTorsionForce: "cmap",
    mm.CustomBondForce: "lj_14",
    mm.NonbondedForce: "coulomb",  # LJ is in the others: CHARMM's NBFIX needs a custom force.
    mm.CustomNonbondedForce: "lj",  # Excluding 1-4 pairs
}
groups = {}
for i, f in enumerate(system.getForces()):
    if type(f) in names:
        f.setForceGroup(i)
        groups[names[type(f)]] = i

context = mm.Context(system, mm.VerletIntegrator(0.001), mm.Platform.getPlatformByName("Reference"))
context.setPositions([mm.Vec3(*p) for p in pos_nm] * unit.nanometer)

nb = next(f for f in system.getForces() if isinstance(f, mm.NonbondedForce))

# 1-4 Coulomb, from NonbondedForce exceptions with a charge product.
coulomb_14 = 0.0
n_14_coulomb = 0
for k in range(nb.getNumExceptions()):
    i, j, qq, _, _ = nb.getExceptionParameters(k)
    qq = qq.value_in_unit(unit.elementary_charge**2)
    if qq != 0:
        r = math.dist(pos_nm[i], pos_nm[j])
        coulomb_14 += ONE_4PI_EPS0 * qq / r
        n_14_coulomb += 1
coulomb_14 *= KJ_TO_KCAL

with open("charmm_ubq_openmm.txt", "w", encoding="utf-8", newline="\n") as out:
    out.write("# CHARMM36m reference: OpenMM 8.3.1, charmm36_2024.xml, 1UBQ with hydrogens at pH 7.\n")
    out.write("# Generated by regenerate_charmm_reference.py. Positions in Å, energies in kcal/mol.\n")
    out.write("# ATOM index res_seq res_name atom_name element x y z charge\n")
    for atom in top.atoms():
        q = nb.getParticleParameters(atom.index)[0].value_in_unit(unit.elementary_charge)
        x, y, z = (10 * v for v in pos_nm[atom.index])
        out.write(
            f"ATOM {atom.index} {atom.residue.id} {atom.residue.name} {atom.name} "
            f"{atom.element.symbol} {x:.4f} {y:.4f} {z:.4f} {q:.4f}\n"
        )
    for bond in top.bonds():
        out.write(f"BOND {bond[0].index} {bond[1].index}\n")

    for name, group in groups.items():
        e = context.getState(getEnergy=True, groups={group}).getPotentialEnergy()
        out.write(f"ENERGY {name} {e.value_in_unit(unit.kilocalorie_per_mole):.6f}\n")
    out.write(f"ENERGY coulomb_14 {coulomb_14:.6f}\n")

    lj14 = next(f for f in system.getForces() if isinstance(f, mm.CustomBondForce))
    ub = next(f for f in system.getForces() if isinstance(f, mm.HarmonicBondForce))
    cmap = next(f for f in system.getForces() if isinstance(f, mm.CMAPTorsionForce))
    impr = next(f for f in system.getForces() if isinstance(f, mm.CustomTorsionForce))
    out.write(f"COUNT bond_ub {ub.getNumBonds()}\n")
    out.write(f"COUNT pairs_14 {lj14.getNumBonds()}\n")
    out.write(f"COUNT pairs_14_coulomb {n_14_coulomb}\n")
    out.write(f"COUNT improper {impr.getNumTorsions()}\n")
    out.write(f"COUNT cmap {cmap.getNumTorsions()}\n")
    out.write(f"COUNT exceptions {nb.getNumExceptions()}\n")

    # Each improper, and its energy. OpenMM orders some impropers among equivalent atoms
    # differently from CHARMM's residue topologies, e.g. Asp's CG CB OD1 OD2 vs CHARMM's
    # CG CB OD2 OD1, which changes their energy.
    for k in range(impr.getNumTorsions()):
        a, b, c, d, (k_psi, psi0) = impr.getTorsionParameters(k)
        psi = torsion_angle(*(pos_nm[i] for i in (a, b, c, d)))
        dpsi = abs(psi - psi0)
        dpsi = min(dpsi, 2 * math.pi - dpsi)
        out.write(f"IMPROPER {a} {b} {c} {d} {k_psi * dpsi**2 * KJ_TO_KCAL:.6f}\n")
