[package]
name = "dynamics_py"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]


[dependencies]
dynamics_rs = { package = "dynamics", path = ".." }
pyo3 = { version = "0.26.0", features = ["extension-module", "abi3-py310"] }
lin_alg = "1.3.6"